<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

use \Drupal\node\NodeInterface;

/**
 * Implement hook_preprocess().
 *
 * Adds useful theme variables.
 */
function ns_bootstrap_preprocess(&$variables, $hook, $info) {
  if (isset($variables['directory'])) {
    $variables['theme_path'] = base_path() . $variables['directory'];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Adds a custom header image to the page template for group project templates.
 */
function ns_bootstrap_preprocess_page(&$variables) {
  if (($node = \Drupal::routeMatch()->getParameter('node')) && $node instanceof NodeInterface && $node->getType() == 'group_project_template') {
    $variables['field_header_image'] = $node->field_header_image->entity->field_media_image->entity->uri->value;
  }
}

/**
 * Implements hook_theme().
 */
function ns_bootstrap_theme($existing, $type, $theme, $path) {
  $info = [
    'views_search_exposed_form' => [
      'render element' => 'form',
      'path' => \Drupal::service('extension.path.resolver')->getPath('theme', 'ns_bootstrap') . '/templates/views',
    ],
  ];
  return $info;
}

/**
 * Add a suggestion for the content type bundle, for group-project pages.
 *
 * {@inheritDoc}
 */
function ns_bootstrap_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
  }
}
